#Application URL
url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#Browser Configuration
browser = chrome

#Credentials
username = admin 
paswword = admin123


#implicitWait(in c=seconds)
implicitWait = 10